# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ff02dcb99a96a9c778429417b7ed30bbd3c68e9e047f7fc8127fc788fa2c3f3d67e3246e58222f66c74c5757961adb38ee1549ff5f98b160aefc406e5a07896

test:
  secret_key_base: 6c32489925caf9b0b6a21a68e20e4020f2436f2cebcadee124c6004884941cebda637d941ffdf3d022e548f19edb471ecc8de4f2a6e4fbbe66ade9bb3988f8e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
